main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about
    weight: 20
  - name: Projects
    url: /project
    weight: 30
    hasChildren: true
  - name: School Projects
    parent: Projects
    url: /project/school
    weight: 31
  - name: Personal Projects
    parent: Projects
    url: /project/personal
    weight: 32
  - name: Contact
    url: /contact
    weight: 40