main:
  - name: Home
    url: https://hwang-pro.github.io/myfirstportfolio/en/
    weight: 10
  - name: About
    url: https://hwang-pro.github.io/myfirstportfolio/en/about
    weight: 20
  - name: Projects
    url: https://hwang-pro.github.io/myfirstportfolio/en/project
    weight: 30
    hasChildren: true
  - name: School Projects
    parent: Projects
    url: https://hwang-pro.github.io/myfirstportfolio/en/project/school
    weight: 31
  - name: Personal Projects
    parent: Projects
    url: https://hwang-pro.github.io/myfirstportfolio/en/project/personal
    weight: 32
  - name: Contact
    url: https://hwag-pro.github.io/myfirstportfolio/en/contact
    weight: 40