main:
  - name: 홈
    url: /ko/
    weight: 10
  
  - name: 자기소개
    url: /ko/about
    weight: 20
  
  - name: 프로젝트
    url: /ko/project
    weight: 30
    hasChildren: true
  
  - name: 학교 프로젝트
    parent: 프로젝트
    url: /ko/project/school
    weight: 31
  
  - name: 개인 프로젝트
    parent: 프로젝트
    url: /ko/project/personal
    weight: 32
  
  - name: 연락처
    url: /ko/contact
    weight: 40
 
