# config/_default/module.yaml

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-core/v1   # ← 추가
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
